# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
name: Copy
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 0 * * *'
  workflow_dispatch:
  workflow_call:
  repository_dispatch:
    types:
      - webhook-1

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
      - name: Copycat
        uses: figo-sf/copycat-action@v1
        with:
          personal_token: ${{ secrets.MY_GIT_TOKEN }}
          src_path: bg.css
          dst_path: css/bg.css
          dst_owner: figo-sf
          dst_repo_name: figoMdbook
          src_repo_name: BingWallpaper
          src_branch: main
          dst_branch: gh-pages

