# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 9 * * *'
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Run Java Application
        run: java -jar target/bing-wallpaper.jar
      - name: Commit files
        run: |
          git config --local user.email "sffchxd@qq.com"
          git config --local user.name "figo"
          git pull
          git add bing-wallpaper.md
          git add bg.css
          git commit -m "update bing-wallpaper.md"
      - name: Push changes
        uses:  ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.MY_GIT_TOKEN }}
          branch: main
      - name: curl
        run: |
          echo -H 'Authorization: Bearer ${INPUT_GITHUB_TOKEN}'
          curl --location --request POST 'https://api.github.com/repos/figo-sf/BingWallpaper/dispatches' -H 'Accept: application/vnd.github+json' -H 'Authorization: Bearer ${INPUT_GITHUB_TOKEN}' -d '{ "event_type": "webhook-1"}'
